name: Artifact

on: push

env:
  ARTIFACT_NAME: hello-artifact

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }} 
        path: . # This uploads all files in the repository